# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.product1 import Product1
from swagger_server.models.product1_disorder_disorder_association import Product1DisorderDisorderAssociation
from swagger_server.models.product1_disorder_flag import Product1DisorderFlag
from swagger_server.models.product1_external_reference import Product1ExternalReference
from swagger_server.models.product1_textual_information import Product1TextualInformation
from swagger_server.models.product3_classification import Product3Classification
from swagger_server.models.product3_classification_list import Product3ClassificationList
from swagger_server.models.product4_hpo import Product4HPO
from swagger_server.models.product4_hpohpo import Product4HPOHPO
from swagger_server.models.product4_hpohpo_disorder_association import Product4HPOHPODisorderAssociation
from swagger_server.models.product6 import Product6
from swagger_server.models.product6_disorder_gene_association import Product6DisorderGeneAssociation
from swagger_server.models.product6_gene import Product6Gene
from swagger_server.models.product6_gene_disorder import Product6GeneDisorder
from swagger_server.models.product6_gene_external_reference import Product6GeneExternalReference
from swagger_server.models.product6_gene_gene_disorder_association import Product6GeneGeneDisorderAssociation
from swagger_server.models.product6_gene_locus import Product6GeneLocus
from swagger_server.models.product9_ages import Product9Ages
from swagger_server.models.product9_prev import Product9Prev
from swagger_server.models.product9_prev_prevalence import Product9PrevPrevalence
