# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Product4HPOHPO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hpo_id: str=None, hpo_term: str=None):  # noqa: E501
        """Product4HPOHPO - a model defined in Swagger

        :param hpo_id: The hpo_id of this Product4HPOHPO.  # noqa: E501
        :type hpo_id: str
        :param hpo_term: The hpo_term of this Product4HPOHPO.  # noqa: E501
        :type hpo_term: str
        """
        self.swagger_types = {
            'hpo_id': str,
            'hpo_term': str
        }

        self.attribute_map = {
            'hpo_id': 'HPOId',
            'hpo_term': 'HPOTerm'
        }
        self._hpo_id = hpo_id
        self._hpo_term = hpo_term

    @classmethod
    def from_dict(cls, dikt) -> 'Product4HPOHPO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product4_HPO_HPO of this Product4HPOHPO.  # noqa: E501
        :rtype: Product4HPOHPO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hpo_id(self) -> str:
        """Gets the hpo_id of this Product4HPOHPO.


        :return: The hpo_id of this Product4HPOHPO.
        :rtype: str
        """
        return self._hpo_id

    @hpo_id.setter
    def hpo_id(self, hpo_id: str):
        """Sets the hpo_id of this Product4HPOHPO.


        :param hpo_id: The hpo_id of this Product4HPOHPO.
        :type hpo_id: str
        """

        self._hpo_id = hpo_id

    @property
    def hpo_term(self) -> str:
        """Gets the hpo_term of this Product4HPOHPO.


        :return: The hpo_term of this Product4HPOHPO.
        :rtype: str
        """
        return self._hpo_term

    @hpo_term.setter
    def hpo_term(self, hpo_term: str):
        """Sets the hpo_term of this Product4HPOHPO.


        :param hpo_term: The hpo_term of this Product4HPOHPO.
        :type hpo_term: str
        """

        self._hpo_term = hpo_term
