# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.product4_hpohpo_disorder_association import Product4HPOHPODisorderAssociation  # noqa: F401,E501
from swagger_server import util


class Product4HPO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, orph_acode: str=None, name: str=None, hpo_disorder_association: List[Product4HPOHPODisorderAssociation]=None):  # noqa: E501
        """Product4HPO - a model defined in Swagger

        :param orph_acode: The orph_acode of this Product4HPO.  # noqa: E501
        :type orph_acode: str
        :param name: The name of this Product4HPO.  # noqa: E501
        :type name: str
        :param hpo_disorder_association: The hpo_disorder_association of this Product4HPO.  # noqa: E501
        :type hpo_disorder_association: List[Product4HPOHPODisorderAssociation]
        """
        self.swagger_types = {
            'orph_acode': str,
            'name': str,
            'hpo_disorder_association': List[Product4HPOHPODisorderAssociation]
        }

        self.attribute_map = {
            'orph_acode': 'ORPHAcode',
            'name': 'Name',
            'hpo_disorder_association': 'HPODisorderAssociation'
        }
        self._orph_acode = orph_acode
        self._name = name
        self._hpo_disorder_association = hpo_disorder_association

    @classmethod
    def from_dict(cls, dikt) -> 'Product4HPO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product4_HPO of this Product4HPO.  # noqa: E501
        :rtype: Product4HPO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def orph_acode(self) -> str:
        """Gets the orph_acode of this Product4HPO.


        :return: The orph_acode of this Product4HPO.
        :rtype: str
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: str):
        """Sets the orph_acode of this Product4HPO.


        :param orph_acode: The orph_acode of this Product4HPO.
        :type orph_acode: str
        """
        if orph_acode is None:
            raise ValueError("Invalid value for `orph_acode`, must not be `None`")  # noqa: E501

        self._orph_acode = orph_acode

    @property
    def name(self) -> str:
        """Gets the name of this Product4HPO.


        :return: The name of this Product4HPO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product4HPO.


        :param name: The name of this Product4HPO.
        :type name: str
        """

        self._name = name

    @property
    def hpo_disorder_association(self) -> List[Product4HPOHPODisorderAssociation]:
        """Gets the hpo_disorder_association of this Product4HPO.


        :return: The hpo_disorder_association of this Product4HPO.
        :rtype: List[Product4HPOHPODisorderAssociation]
        """
        return self._hpo_disorder_association

    @hpo_disorder_association.setter
    def hpo_disorder_association(self, hpo_disorder_association: List[Product4HPOHPODisorderAssociation]):
        """Sets the hpo_disorder_association of this Product4HPO.


        :param hpo_disorder_association: The hpo_disorder_association of this Product4HPO.
        :type hpo_disorder_association: List[Product4HPOHPODisorderAssociation]
        """

        self._hpo_disorder_association = hpo_disorder_association
