# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.product4_hpohpo import Product4HPOHPO  # noqa: F401,E501
from swagger_server import util


class Product4HPOHPODisorderAssociation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hpo: Product4HPOHPO=None, hpo_frequency: str=None, diagnostic_criteria: str=None):  # noqa: E501
        """Product4HPOHPODisorderAssociation - a model defined in Swagger

        :param hpo: The hpo of this Product4HPOHPODisorderAssociation.  # noqa: E501
        :type hpo: Product4HPOHPO
        :param hpo_frequency: The hpo_frequency of this Product4HPOHPODisorderAssociation.  # noqa: E501
        :type hpo_frequency: str
        :param diagnostic_criteria: The diagnostic_criteria of this Product4HPOHPODisorderAssociation.  # noqa: E501
        :type diagnostic_criteria: str
        """
        self.swagger_types = {
            'hpo': Product4HPOHPO,
            'hpo_frequency': str,
            'diagnostic_criteria': str
        }

        self.attribute_map = {
            'hpo': 'HPO',
            'hpo_frequency': 'HPOFrequency',
            'diagnostic_criteria': 'DiagnosticCriteria'
        }
        self._hpo = hpo
        self._hpo_frequency = hpo_frequency
        self._diagnostic_criteria = diagnostic_criteria

    @classmethod
    def from_dict(cls, dikt) -> 'Product4HPOHPODisorderAssociation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product4_HPO_HPODisorderAssociation of this Product4HPOHPODisorderAssociation.  # noqa: E501
        :rtype: Product4HPOHPODisorderAssociation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hpo(self) -> Product4HPOHPO:
        """Gets the hpo of this Product4HPOHPODisorderAssociation.


        :return: The hpo of this Product4HPOHPODisorderAssociation.
        :rtype: Product4HPOHPO
        """
        return self._hpo

    @hpo.setter
    def hpo(self, hpo: Product4HPOHPO):
        """Sets the hpo of this Product4HPOHPODisorderAssociation.


        :param hpo: The hpo of this Product4HPOHPODisorderAssociation.
        :type hpo: Product4HPOHPO
        """

        self._hpo = hpo

    @property
    def hpo_frequency(self) -> str:
        """Gets the hpo_frequency of this Product4HPOHPODisorderAssociation.


        :return: The hpo_frequency of this Product4HPOHPODisorderAssociation.
        :rtype: str
        """
        return self._hpo_frequency

    @hpo_frequency.setter
    def hpo_frequency(self, hpo_frequency: str):
        """Sets the hpo_frequency of this Product4HPOHPODisorderAssociation.


        :param hpo_frequency: The hpo_frequency of this Product4HPOHPODisorderAssociation.
        :type hpo_frequency: str
        """

        self._hpo_frequency = hpo_frequency

    @property
    def diagnostic_criteria(self) -> str:
        """Gets the diagnostic_criteria of this Product4HPOHPODisorderAssociation.


        :return: The diagnostic_criteria of this Product4HPOHPODisorderAssociation.
        :rtype: str
        """
        return self._diagnostic_criteria

    @diagnostic_criteria.setter
    def diagnostic_criteria(self, diagnostic_criteria: str):
        """Sets the diagnostic_criteria of this Product4HPOHPODisorderAssociation.


        :param diagnostic_criteria: The diagnostic_criteria of this Product4HPOHPODisorderAssociation.
        :type diagnostic_criteria: str
        """

        self._diagnostic_criteria = diagnostic_criteria
