# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Product3Classification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, orph_acode: str=None, hch_id: str=None, parents: List[str]=None, childs: List[str]=None):  # noqa: E501
        """Product3Classification - a model defined in Swagger

        :param name: The name of this Product3Classification.  # noqa: E501
        :type name: str
        :param orph_acode: The orph_acode of this Product3Classification.  # noqa: E501
        :type orph_acode: str
        :param hch_id: The hch_id of this Product3Classification.  # noqa: E501
        :type hch_id: str
        :param parents: The parents of this Product3Classification.  # noqa: E501
        :type parents: List[str]
        :param childs: The childs of this Product3Classification.  # noqa: E501
        :type childs: List[str]
        """
        self.swagger_types = {
            'name': str,
            'orph_acode': str,
            'hch_id': str,
            'parents': List[str],
            'childs': List[str]
        }

        self.attribute_map = {
            'name': 'name',
            'orph_acode': 'ORPHAcode',
            'hch_id': 'hch_id',
            'parents': 'parents',
            'childs': 'childs'
        }
        self._name = name
        self._orph_acode = orph_acode
        self._hch_id = hch_id
        self._parents = parents
        self._childs = childs

    @classmethod
    def from_dict(cls, dikt) -> 'Product3Classification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product3_classification of this Product3Classification.  # noqa: E501
        :rtype: Product3Classification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Product3Classification.


        :return: The name of this Product3Classification.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product3Classification.


        :param name: The name of this Product3Classification.
        :type name: str
        """

        self._name = name

    @property
    def orph_acode(self) -> str:
        """Gets the orph_acode of this Product3Classification.


        :return: The orph_acode of this Product3Classification.
        :rtype: str
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: str):
        """Sets the orph_acode of this Product3Classification.


        :param orph_acode: The orph_acode of this Product3Classification.
        :type orph_acode: str
        """
        if orph_acode is None:
            raise ValueError("Invalid value for `orph_acode`, must not be `None`")  # noqa: E501

        self._orph_acode = orph_acode

    @property
    def hch_id(self) -> str:
        """Gets the hch_id of this Product3Classification.


        :return: The hch_id of this Product3Classification.
        :rtype: str
        """
        return self._hch_id

    @hch_id.setter
    def hch_id(self, hch_id: str):
        """Sets the hch_id of this Product3Classification.


        :param hch_id: The hch_id of this Product3Classification.
        :type hch_id: str
        """

        self._hch_id = hch_id

    @property
    def parents(self) -> List[str]:
        """Gets the parents of this Product3Classification.


        :return: The parents of this Product3Classification.
        :rtype: List[str]
        """
        return self._parents

    @parents.setter
    def parents(self, parents: List[str]):
        """Sets the parents of this Product3Classification.


        :param parents: The parents of this Product3Classification.
        :type parents: List[str]
        """

        self._parents = parents

    @property
    def childs(self) -> List[str]:
        """Gets the childs of this Product3Classification.


        :return: The childs of this Product3Classification.
        :rtype: List[str]
        """
        return self._childs

    @childs.setter
    def childs(self, childs: List[str]):
        """Sets the childs of this Product3Classification.


        :param childs: The childs of this Product3Classification.
        :type childs: List[str]
        """

        self._childs = childs
