version: "3.9"
services:
  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - orpha-net
    ports:
      - 9200:9200
  orphadata:
    container_name: api-orphadata
    image: orphanet/orphadata
    environment:
      - ELASTIC_URL=http://es:9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASS=changeme
    networks:
      - orpha-net
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000
networks:
  orpha-net:
    driver: bridge