openapi: 3.0.1
info:
  title: Orphadata API
  version: 1.0.0
  description: Provide API to Orphadata
  termsOfService: https://www.orpha.net/consor/cgi-bin/Education_AboutOrphanet.php?lng=EN
  license:
    name: CC-BY-NC-SA
    url: 'https://creativecommons.org/licenses/by-nc-sa/3.0/fr/'
  contact:
    email: cyril.bigot@inserm.fr
    name: maintainer
externalDocs:
  url: 'http://www.orphadata.org/cgi-bin/index.php'
  description: 'For further information, checks Orphadata main site'
servers:
  - url: "/"
    variables: {}
    description: URL for Orphadata's API server
tags:
  - name: disorder
    description: Full list of API operation
    externalDocs:
      description: Disorder or Disease object according to Orphanet Ontology
      url: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C2991&viewMode=All&siblings=false
  - name: orphaclassif
    description: Hierarchical classification
    externalDocs:
      description: Orphanet's hierarchical classification of disorder 
      url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
  - name: product1
    description: Operations for product 1
    externalDocs:
      description: Disorder or Disease object according to Orphanet Ontology
      url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
  - name: associated gene
    description: Operations for associated genes
    externalDocs:
      description: Genes referenced by Orphanet
      url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
  - name: phenotype
    description: Operations for phenotype
    externalDocs:
      description: Phenotypes referenced by Orphanet, Human Phenotype Ontology (HPO)
      url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
  - name: epidemiology
    description: Operations for epidemiology
    externalDocs:
      description: Epidemiological data referenced by Orphanet
      url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
components:
  schemas:
    disorder:
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "558"
        name:
          type: string
          example: "Marfan syndrome"
        hierarchyId:
          type: string
          example: "146"
        parents:
          type: array
          items:
            type: string
            example: ["93890"]
        childs:
          type: array
          items:
            type: string
            example: ["284963", "284973"]
      required:
        - ORPHAcode
  responses:
    "default":
      description: Unknown internal error
    "403":
      description: Access denied
    "404":
      description: Queried disorder not found
  parameters:
    orphacode:
      name: orphacode
      description: The ORPHAcode is a unique identifier to reference an Orphanet's concept
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
        exclusiveMinimum: true
    language:
      name: language
      description: Specify the language in the list supported by Orphanet (EN, FR, ES, DE, IT, PT, NL, PL)
      in: path
      required: true
      schema:
        enum:
          - EN
          - FR
          - ES
          - DE
          - IT
          - PT
          - NL
          - PL
        default: EN
paths:
  /orphaclassif/orphacode/{orphacode}:
    parameters:
      - $ref: "#/components/parameters/orphacode"
    get:
      summary: Hierarchical classification of disorder by ORPHAcode
      description: Query one disorder by its ORPHAcode and gives its Orphanet classification number, the list of its children and parents.
      operationId: hierarchy_by_orphacode
      tags:
        - disorder
        - orphaclassif
      responses:
        "default":
          $ref: "#/components/responses/default"
        "200":
          description: Successful operation
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/default"
  /product1/orphacode/{orphacode}/{language}:
    parameters:
      - $ref: "#/components/parameters/orphacode"
      - $ref: "#/components/parameters/language"
    get:
      summary: Disorder by ORPHAcode for product 1
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: disorder_by_orphacode
      tags:
        - disorder
        - product1
      responses:
        "default":
          $ref: "#/components/responses/default"
        "200":
          description: Successful operation
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/default"
  /associatedgene/orphacode/{orphacode}:
    parameters:
      - $ref: "#/components/parameters/orphacode"
    get:
      summary: Disorder by ORPHAcode with associated genes
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: gene_by_disorder_orphacode
      tags:
        - disorder
        - associated gene
      responses:
        "default":
          $ref: "#/components/responses/default"
        "200":
          description: Successful operation
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/default"
  /phenotype/orphacode/{orphacode}/{language}:
    parameters:
      - $ref: "#/components/parameters/orphacode"
      - $ref: "#/components/parameters/language"
    get:
      summary: Disorder by ORPHAcode with its associated phenotype
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: phenotype_by_orphacode
      tags:
        - disorder
        - phenotype
      responses:
        "default":
          $ref: "#/components/responses/default"
        "200":
          description: Successful operation
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/default"
  /epidemiology/orphacode/{orphacode}/{language}:
    parameters:
      - $ref: "#/components/parameters/orphacode"
      - $ref: '#/components/parameters/language'
    get:
      summary: Disorder by ORPHAcode with epidemiological data
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: epidemiology_by_orphacode
      tags:
        - disorder
        - epidemiology
      responses:
        "default":
          $ref: "#/components/responses/default"
        "200":
          description: Successful operation
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/default"
  /age/orphacode/{orphacode}/{language}:
    parameters:
      - $ref: "#/components/parameters/orphacode"
      - $ref: '#/components/parameters/language'
    get:
      summary: Disorder by ORPHAcode with age of onset
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: age_by_orphacode
      tags:
        - disorder
        - epidemiology
      responses:
        "default":
          $ref: "#/components/responses/default"
        "200":
          description: Successful operation
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/default"