# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Product1DisorderFlag(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, label: str=None):  # noqa: E501
        """Product1DisorderFlag - a model defined in Swagger

        :param label: The label of this Product1DisorderFlag.  # noqa: E501
        :type label: str
        """
        self.swagger_types = {
            'label': str
        }

        self.attribute_map = {
            'label': 'Label'
        }
        self._label = label

    @classmethod
    def from_dict(cls, dikt) -> 'Product1DisorderFlag':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product1_DisorderFlag of this Product1DisorderFlag.  # noqa: E501
        :rtype: Product1DisorderFlag
        """
        return util.deserialize_model(dikt, cls)

    @property
    def label(self) -> str:
        """Gets the label of this Product1DisorderFlag.


        :return: The label of this Product1DisorderFlag.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this Product1DisorderFlag.


        :param label: The label of this Product1DisorderFlag.
        :type label: str
        """

        self._label = label
