# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server.models.product1_disorder2 import Product1Disorder2  # noqa: F401,E501
from swagger_server import util


class Product1DisorderDisorderAssociation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, disorder1: str=None, disorder2: Product1Disorder2=None, disorder_disorder_association_type: str=None):  # noqa: E501
        """Product1DisorderDisorderAssociation - a model defined in Swagger

        :param disorder1: The disorder1 of this Product1DisorderDisorderAssociation.  # noqa: E501
        :type disorder1: str
        :param disorder2: The disorder2 of this Product1DisorderDisorderAssociation.  # noqa: E501
        :type disorder2: Product1Disorder2
        :param disorder_disorder_association_type: The disorder_disorder_association_type of this Product1DisorderDisorderAssociation.  # noqa: E501
        :type disorder_disorder_association_type: str
        """
        self.swagger_types = {
            'disorder1': str,
            'disorder2': Product1Disorder2,
            'disorder_disorder_association_type': str
        }

        self.attribute_map = {
            'disorder1': 'Disorder1',
            'disorder2': 'Disorder2',
            'disorder_disorder_association_type': 'DisorderDisorderAssociationType'
        }
        self._disorder1 = disorder1
        self._disorder2 = disorder2
        self._disorder_disorder_association_type = disorder_disorder_association_type

    @classmethod
    def from_dict(cls, dikt) -> 'Product1DisorderDisorderAssociation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product1_DisorderDisorderAssociation of this Product1DisorderDisorderAssociation.  # noqa: E501
        :rtype: Product1DisorderDisorderAssociation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def disorder1(self) -> str:
        """Gets the disorder1 of this Product1DisorderDisorderAssociation.


        :return: The disorder1 of this Product1DisorderDisorderAssociation.
        :rtype: str
        """
        return self._disorder1

    @disorder1.setter
    def disorder1(self, disorder1: str):
        """Sets the disorder1 of this Product1DisorderDisorderAssociation.


        :param disorder1: The disorder1 of this Product1DisorderDisorderAssociation.
        :type disorder1: str
        """

        self._disorder1 = disorder1

    @property
    def disorder2(self) -> Product1Disorder2:
        """Gets the disorder2 of this Product1DisorderDisorderAssociation.


        :return: The disorder2 of this Product1DisorderDisorderAssociation.
        :rtype: Product1Disorder2
        """
        return self._disorder2

    @disorder2.setter
    def disorder2(self, disorder2: Product1Disorder2):
        """Sets the disorder2 of this Product1DisorderDisorderAssociation.


        :param disorder2: The disorder2 of this Product1DisorderDisorderAssociation.
        :type disorder2: Product1Disorder2
        """

        self._disorder2 = disorder2

    @property
    def disorder_disorder_association_type(self) -> str:
        """Gets the disorder_disorder_association_type of this Product1DisorderDisorderAssociation.


        :return: The disorder_disorder_association_type of this Product1DisorderDisorderAssociation.
        :rtype: str
        """
        return self._disorder_disorder_association_type

    @disorder_disorder_association_type.setter
    def disorder_disorder_association_type(self, disorder_disorder_association_type: str):
        """Sets the disorder_disorder_association_type of this Product1DisorderDisorderAssociation.


        :param disorder_disorder_association_type: The disorder_disorder_association_type of this Product1DisorderDisorderAssociation.
        :type disorder_disorder_association_type: str
        """

        self._disorder_disorder_association_type = disorder_disorder_association_type
