# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Product6GeneLocus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, gene_locus: str=None, locus_key: str=None):  # noqa: E501
        """Product6GeneLocus - a model defined in Swagger

        :param gene_locus: The gene_locus of this Product6GeneLocus.  # noqa: E501
        :type gene_locus: str
        :param locus_key: The locus_key of this Product6GeneLocus.  # noqa: E501
        :type locus_key: str
        """
        self.swagger_types = {
            'gene_locus': str,
            'locus_key': str
        }

        self.attribute_map = {
            'gene_locus': 'GeneLocus',
            'locus_key': 'LocusKey'
        }
        self._gene_locus = gene_locus
        self._locus_key = locus_key

    @classmethod
    def from_dict(cls, dikt) -> 'Product6GeneLocus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product6_Gene_Locus of this Product6GeneLocus.  # noqa: E501
        :rtype: Product6GeneLocus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gene_locus(self) -> str:
        """Gets the gene_locus of this Product6GeneLocus.


        :return: The gene_locus of this Product6GeneLocus.
        :rtype: str
        """
        return self._gene_locus

    @gene_locus.setter
    def gene_locus(self, gene_locus: str):
        """Sets the gene_locus of this Product6GeneLocus.


        :param gene_locus: The gene_locus of this Product6GeneLocus.
        :type gene_locus: str
        """

        self._gene_locus = gene_locus

    @property
    def locus_key(self) -> str:
        """Gets the locus_key of this Product6GeneLocus.


        :return: The locus_key of this Product6GeneLocus.
        :rtype: str
        """
        return self._locus_key

    @locus_key.setter
    def locus_key(self, locus_key: str):
        """Sets the locus_key of this Product6GeneLocus.


        :param locus_key: The locus_key of this Product6GeneLocus.
        :type locus_key: str
        """

        self._locus_key = locus_key
