# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server.models.product6_gene_disorder import Product6GeneDisorder  # noqa: F401,E501
from swagger_server import util


class Product6GeneGeneDisorderAssociation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source_of_validation: str=None, disorder_gene_association_type: str=None, disorder_gene_association_status: str=None, disorder: Product6GeneDisorder=None):  # noqa: E501
        """Product6GeneGeneDisorderAssociation - a model defined in Swagger

        :param source_of_validation: The source_of_validation of this Product6GeneGeneDisorderAssociation.  # noqa: E501
        :type source_of_validation: str
        :param disorder_gene_association_type: The disorder_gene_association_type of this Product6GeneGeneDisorderAssociation.  # noqa: E501
        :type disorder_gene_association_type: str
        :param disorder_gene_association_status: The disorder_gene_association_status of this Product6GeneGeneDisorderAssociation.  # noqa: E501
        :type disorder_gene_association_status: str
        :param disorder: The disorder of this Product6GeneGeneDisorderAssociation.  # noqa: E501
        :type disorder: Product6GeneDisorder
        """
        self.swagger_types = {
            'source_of_validation': str,
            'disorder_gene_association_type': str,
            'disorder_gene_association_status': str,
            'disorder': Product6GeneDisorder
        }

        self.attribute_map = {
            'source_of_validation': 'SourceOfValidation',
            'disorder_gene_association_type': 'DisorderGeneAssociationType',
            'disorder_gene_association_status': 'DisorderGeneAssociationStatus',
            'disorder': 'disorder'
        }
        self._source_of_validation = source_of_validation
        self._disorder_gene_association_type = disorder_gene_association_type
        self._disorder_gene_association_status = disorder_gene_association_status
        self._disorder = disorder

    @classmethod
    def from_dict(cls, dikt) -> 'Product6GeneGeneDisorderAssociation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product6_gene_GeneDisorderAssociation of this Product6GeneGeneDisorderAssociation.  # noqa: E501
        :rtype: Product6GeneGeneDisorderAssociation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_of_validation(self) -> str:
        """Gets the source_of_validation of this Product6GeneGeneDisorderAssociation.


        :return: The source_of_validation of this Product6GeneGeneDisorderAssociation.
        :rtype: str
        """
        return self._source_of_validation

    @source_of_validation.setter
    def source_of_validation(self, source_of_validation: str):
        """Sets the source_of_validation of this Product6GeneGeneDisorderAssociation.


        :param source_of_validation: The source_of_validation of this Product6GeneGeneDisorderAssociation.
        :type source_of_validation: str
        """

        self._source_of_validation = source_of_validation

    @property
    def disorder_gene_association_type(self) -> str:
        """Gets the disorder_gene_association_type of this Product6GeneGeneDisorderAssociation.


        :return: The disorder_gene_association_type of this Product6GeneGeneDisorderAssociation.
        :rtype: str
        """
        return self._disorder_gene_association_type

    @disorder_gene_association_type.setter
    def disorder_gene_association_type(self, disorder_gene_association_type: str):
        """Sets the disorder_gene_association_type of this Product6GeneGeneDisorderAssociation.


        :param disorder_gene_association_type: The disorder_gene_association_type of this Product6GeneGeneDisorderAssociation.
        :type disorder_gene_association_type: str
        """

        self._disorder_gene_association_type = disorder_gene_association_type

    @property
    def disorder_gene_association_status(self) -> str:
        """Gets the disorder_gene_association_status of this Product6GeneGeneDisorderAssociation.


        :return: The disorder_gene_association_status of this Product6GeneGeneDisorderAssociation.
        :rtype: str
        """
        return self._disorder_gene_association_status

    @disorder_gene_association_status.setter
    def disorder_gene_association_status(self, disorder_gene_association_status: str):
        """Sets the disorder_gene_association_status of this Product6GeneGeneDisorderAssociation.


        :param disorder_gene_association_status: The disorder_gene_association_status of this Product6GeneGeneDisorderAssociation.
        :type disorder_gene_association_status: str
        """

        self._disorder_gene_association_status = disorder_gene_association_status

    @property
    def disorder(self) -> Product6GeneDisorder:
        """Gets the disorder of this Product6GeneGeneDisorderAssociation.


        :return: The disorder of this Product6GeneGeneDisorderAssociation.
        :rtype: Product6GeneDisorder
        """
        return self._disorder

    @disorder.setter
    def disorder(self, disorder: Product6GeneDisorder):
        """Sets the disorder of this Product6GeneGeneDisorderAssociation.


        :param disorder: The disorder of this Product6GeneGeneDisorderAssociation.
        :type disorder: Product6GeneDisorder
        """

        self._disorder = disorder
