openapi: 3.0.1
info:
  title: Orphadata API
  description: Provide API to Orphadata
  termsOfService: https://www.orpha.net/consor/cgi-bin/Education_AboutOrphanet.php?lng=EN
  contact:
    name: maintainer
    email: cyril.bigot@inserm.fr
  license:
    name: CC-BY-NC-SA
    url: https://creativecommons.org/licenses/by-nc-sa/3.0/fr/
  version: 1.0.0
externalDocs:
  description: For further information, checks Orphadata main site
  url: http://www.orphadata.org/cgi-bin/index.php
servers:
- url: /
  description: URL for Orphadata's API server
tags:
- name: disorder
  description: Full list of API operation
  externalDocs:
    description: Disorder or Disease object according to Orphanet Ontology
    url: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C2991&viewMode=All&siblings=false
- name: orphaclassif
  description: Hierarchical classification
  externalDocs:
    description: Orphanet's hierarchical classification of disorder
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: product1
  description: Operations for product 1
  externalDocs:
    description: Disorder or Disease object according to Orphanet Ontology
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: associated gene
  description: Operations for associated genes
  externalDocs:
    description: Genes referenced by Orphanet
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: phenotype
  description: Operations for phenotype
  externalDocs:
    description: Phenotypes referenced by Orphanet, Human Phenotype Ontology (HPO)
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
- name: epidemiology
  description: Operations for epidemiology
  externalDocs:
    description: Epidemiological data referenced by Orphanet
    url: http://www.orphadata.org/cgi-bin/img/PDF/Catalogue_Orphadata.pdf
paths:
  /orphaclassif/orphacode/{orphacode}:
    get:
      tags:
      - disorder
      - orphaclassif
      summary: Hierarchical classification of disorder by ORPHAcode
      description: Query one disorder by its ORPHAcode and gives its Orphanet classification
        number, the list of its children and parents.
      operationId: hierarchy_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      responses:
        "200":
          description: Successful operation
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.disorder_controller
  /product1/orphacode/{orphacode}/{language}:
    get:
      tags:
      - disorder
      - product1
      summary: Disorder by ORPHAcode for product 1
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: disorder_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (EN, FR,
          ES, DE, IT, PT, NL, PL)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - EN
          - FR
          - ES
          - DE
          - IT
          - PT
          - NL
          - PL
      responses:
        "200":
          description: Successful operation
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.disorder_controller
  /associatedgene/orphacode/{orphacode}:
    get:
      tags:
      - disorder
      - associated gene
      summary: Disorder by ORPHAcode with associated genes
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: gene_by_disorder_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      responses:
        "200":
          description: Successful operation
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.disorder_controller
  /phenotype/orphacode/{orphacode}/{language}:
    get:
      tags:
      - disorder
      - phenotype
      summary: Disorder by ORPHAcode with its associated phenotype
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: phenotype_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (EN, FR,
          ES, DE, IT, PT, NL, PL)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - EN
          - FR
          - ES
          - DE
          - IT
          - PT
          - NL
          - PL
      responses:
        "200":
          description: Successful operation
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.disorder_controller
  /epidemiology/orphacode/{orphacode}/{language}:
    get:
      tags:
      - disorder
      - epidemiology
      summary: Disorder by ORPHAcode with epidemiological data
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: epidemiology_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (EN, FR,
          ES, DE, IT, PT, NL, PL)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - EN
          - FR
          - ES
          - DE
          - IT
          - PT
          - NL
          - PL
      responses:
        "200":
          description: Successful operation
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.disorder_controller
  /age/orphacode/{orphacode}/{language}:
    get:
      tags:
      - disorder
      - epidemiology
      summary: Disorder by ORPHAcode with age of onset
      description: Access every information related to a disorder object by its ORPHAcode
      operationId: age_by_orphacode
      parameters:
      - name: orphacode
        in: path
        description: The ORPHAcode is a unique identifier to reference an Orphanet's
          concept
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      - name: language
        in: path
        description: Specify the language in the list supported by Orphanet (EN, FR,
          ES, DE, IT, PT, NL, PL)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: EN
          enum:
          - EN
          - FR
          - ES
          - DE
          - IT
          - PT
          - NL
          - PL
      responses:
        "200":
          description: Successful operation
        "403":
          description: Access denied
        "404":
          description: Queried disorder not found
        "500":
          description: Unknown internal error
        default:
          description: Unknown internal error
      x-openapi-router-controller: swagger_server.controllers.disorder_controller
components:
  schemas:
    disorder:
      required:
      - ORPHAcode
      type: object
      properties:
        ORPHAcode:
          type: string
          example: "558"
        name:
          type: string
          example: Marfan syndrome
        hierarchyId:
          type: string
          example: "146"
        parents:
          type: array
          items:
            type: string
            example: '["93890"]'
        childs:
          type: array
          items:
            type: string
            example: '["284963","284973"]'
  responses:
    "403":
      description: Access denied
    "404":
      description: Queried disorder not found
    default:
      description: Unknown internal error
  parameters:
    orphacode:
      name: orphacode
      in: path
      description: The ORPHAcode is a unique identifier to reference an Orphanet's
        concept
      required: true
      style: simple
      explode: false
      schema:
        minimum: 0
        exclusiveMinimum: true
        type: integer
        format: int32
    language:
      name: language
      in: path
      description: Specify the language in the list supported by Orphanet (EN, FR,
        ES, DE, IT, PT, NL, PL)
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: EN
        enum:
        - EN
        - FR
        - ES
        - DE
        - IT
        - PT
        - NL
        - PL

