openapi: 3.0.1
info:
  title: Orphadata API
  description: Provide API to Orphadata
  termsOfService: TermsOfService
  contact:
    name: maintainer
    email: cyril.bigot@inserm.fr
  license:
    name: CC-BY-NC-SA
  version: 1.0.0
externalDocs:
  description: For further information, checks Orphadata main site
  url: http://www.orphadata.org/cgi-bin/index.php
servers:
- url: /
  description: URL for Orphadata's API server
tags:
- name: disorder
  description: Disorder or Disease object
  externalDocs:
    description: Disorder or Disease object according to Orphanet Ontology
    url: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C2991&viewMode=All&siblings=false
paths:
  /disorder/{orphaNumber}:
    summary: Disorder by orphaNumber
    description: Access informations related to a disorder object by its ORPHAnumber
    get:
      tags:
      - disorder
      summary: Disorder by ORPHAnumber
      description: Access informations related to a disorder object by its ORPHAnumber
      operationId: disorder_by_orphanumber
      parameters:
      - name: orphaNumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
      responses:
        "200":
          description: Successful operation
        default:
          description: Default error sample response
      x-openapi-router-controller: swagger_server.controllers.disorder_controller
components:
  schemas:
    disorder:
      required:
      - ORPHAnumber
      type: object
      properties:
        ORPHAnumber:
          type: string
          example: "558"
        name:
          type: string
          example: Marfan syndrome
        hierarchyId:
          type: string
          example: "146"
        parents:
          type: array
          items:
            type: string
            example: '["93890"]'
        childs:
          type: array
          items:
            type: string
            example: '["284963","284973"]'

