# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from api.models.list_hchid import ListHchid
from api.models.list_orphacode import ListOrphacode
from api.models.list_symbol import ListSymbol
from api.models.product1 import Product1
from api.models.product1_disorder2 import Product1Disorder2
from api.models.product1_disorder_disorder_association import Product1DisorderDisorderAssociation
from api.models.product1_disorder_flag import Product1DisorderFlag
from api.models.product1_disorder_mapping_relation import Product1DisorderMappingRelation
from api.models.product1_disorder_mapping_validation_status import Product1DisorderMappingValidationStatus
from api.models.product1_disorder_type import Product1DisorderType
from api.models.product1_external_reference import Product1ExternalReference
from api.models.product1_list import Product1List
from api.models.product1_textual_information import Product1TextualInformation
from api.models.product3 import Product3
from api.models.product3_classification_list import Product3ClassificationList
from api.models.product4 import Product4
from api.models.product4_disorder import Product4Disorder
from api.models.product4_disorder_hpo import Product4DisorderHPO
from api.models.product4_disorder_hpo_disorder_association import Product4DisorderHPODisorderAssociation
from api.models.product4_list import Product4List
from api.models.product6 import Product6
from api.models.product6_disorder_gene_association import Product6DisorderGeneAssociation
from api.models.product6_gene import Product6Gene
from api.models.product6_gene_disorder import Product6GeneDisorder
from api.models.product6_gene_external_reference import Product6GeneExternalReference
from api.models.product6_gene_gene_disorder_association import Product6GeneGeneDisorderAssociation
from api.models.product6_gene_list import Product6GeneList
from api.models.product6_gene_locus import Product6GeneLocus
from api.models.product6_list import Product6List
from api.models.product9_ages import Product9Ages
from api.models.product9_ages_list import Product9AgesList
from api.models.product9_prev import Product9Prev
from api.models.product9_prev_list import Product9PrevList
from api.models.product9_prev_prevalence import Product9PrevPrevalence
