# coding: utf-8

from __future__ import absolute_import

from api.models.base_model_ import Model
from api import util


class ListOrphacode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """ListOrphacode - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ListOrphacode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The list_orphacode of this ListOrphacode.  # noqa: E501
        :rtype: ListOrphacode
        """
        return util.deserialize_model(dikt, cls)
