# coding: utf-8

from __future__ import absolute_import

from api.models.base_model_ import Model
from api import util


class Product4List(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """Product4List - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Product4List':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product4_list of this Product4List.  # noqa: E501
        :rtype: Product4List
        """
        return util.deserialize_model(dikt, cls)
