# coding: utf-8

from __future__ import absolute_import

from api.models.base_model_ import Model
from api.models.product6_gene import Product6Gene  # noqa: F401,E501
from api import util


class Product6DisorderGeneAssociation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source_of_validation: str=None, gene: Product6Gene=None, disorder_gene_association_type: str=None, disorder_gene_association_status: str=None):  # noqa: E501
        """Product6DisorderGeneAssociation - a model defined in Swagger

        :param source_of_validation: The source_of_validation of this Product6DisorderGeneAssociation.  # noqa: E501
        :type source_of_validation: str
        :param gene: The gene of this Product6DisorderGeneAssociation.  # noqa: E501
        :type gene: Product6Gene
        :param disorder_gene_association_type: The disorder_gene_association_type of this Product6DisorderGeneAssociation.  # noqa: E501
        :type disorder_gene_association_type: str
        :param disorder_gene_association_status: The disorder_gene_association_status of this Product6DisorderGeneAssociation.  # noqa: E501
        :type disorder_gene_association_status: str
        """
        self.swagger_types = {
            'source_of_validation': str,
            'gene': Product6Gene,
            'disorder_gene_association_type': str,
            'disorder_gene_association_status': str
        }

        self.attribute_map = {
            'source_of_validation': 'SourceOfValidation',
            'gene': 'Gene',
            'disorder_gene_association_type': 'DisorderGeneAssociationType',
            'disorder_gene_association_status': 'DisorderGeneAssociationStatus'
        }
        self._source_of_validation = source_of_validation
        self._gene = gene
        self._disorder_gene_association_type = disorder_gene_association_type
        self._disorder_gene_association_status = disorder_gene_association_status

    @classmethod
    def from_dict(cls, dikt) -> 'Product6DisorderGeneAssociation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product6_DisorderGeneAssociation of this Product6DisorderGeneAssociation.  # noqa: E501
        :rtype: Product6DisorderGeneAssociation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_of_validation(self) -> str:
        """Gets the source_of_validation of this Product6DisorderGeneAssociation.


        :return: The source_of_validation of this Product6DisorderGeneAssociation.
        :rtype: str
        """
        return self._source_of_validation

    @source_of_validation.setter
    def source_of_validation(self, source_of_validation: str):
        """Sets the source_of_validation of this Product6DisorderGeneAssociation.


        :param source_of_validation: The source_of_validation of this Product6DisorderGeneAssociation.
        :type source_of_validation: str
        """

        self._source_of_validation = source_of_validation

    @property
    def gene(self) -> Product6Gene:
        """Gets the gene of this Product6DisorderGeneAssociation.


        :return: The gene of this Product6DisorderGeneAssociation.
        :rtype: Product6Gene
        """
        return self._gene

    @gene.setter
    def gene(self, gene: Product6Gene):
        """Sets the gene of this Product6DisorderGeneAssociation.


        :param gene: The gene of this Product6DisorderGeneAssociation.
        :type gene: Product6Gene
        """

        self._gene = gene

    @property
    def disorder_gene_association_type(self) -> str:
        """Gets the disorder_gene_association_type of this Product6DisorderGeneAssociation.


        :return: The disorder_gene_association_type of this Product6DisorderGeneAssociation.
        :rtype: str
        """
        return self._disorder_gene_association_type

    @disorder_gene_association_type.setter
    def disorder_gene_association_type(self, disorder_gene_association_type: str):
        """Sets the disorder_gene_association_type of this Product6DisorderGeneAssociation.


        :param disorder_gene_association_type: The disorder_gene_association_type of this Product6DisorderGeneAssociation.
        :type disorder_gene_association_type: str
        """

        self._disorder_gene_association_type = disorder_gene_association_type

    @property
    def disorder_gene_association_status(self) -> str:
        """Gets the disorder_gene_association_status of this Product6DisorderGeneAssociation.


        :return: The disorder_gene_association_status of this Product6DisorderGeneAssociation.
        :rtype: str
        """
        return self._disorder_gene_association_status

    @disorder_gene_association_status.setter
    def disorder_gene_association_status(self, disorder_gene_association_status: str):
        """Sets the disorder_gene_association_status of this Product6DisorderGeneAssociation.


        :param disorder_gene_association_status: The disorder_gene_association_status of this Product6DisorderGeneAssociation.
        :type disorder_gene_association_status: str
        """

        self._disorder_gene_association_status = disorder_gene_association_status
