# coding: utf-8

from __future__ import absolute_import

from api.models.base_model_ import Model
from api import util


class Product1TextualInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, definition: str=None):  # noqa: E501
        """Product1TextualInformation - a model defined in Swagger

        :param definition: The definition of this Product1TextualInformation.  # noqa: E501
        :type definition: str
        """
        self.swagger_types = {
            'definition': str
        }

        self.attribute_map = {
            'definition': 'Definition'
        }
        self._definition = definition

    @classmethod
    def from_dict(cls, dikt) -> 'Product1TextualInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The product1_TextualInformation of this Product1TextualInformation.  # noqa: E501
        :rtype: Product1TextualInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def definition(self) -> str:
        """Gets the definition of this Product1TextualInformation.


        :return: The definition of this Product1TextualInformation.
        :rtype: str
        """
        return self._definition

    @definition.setter
    def definition(self, definition: str):
        """Sets the definition of this Product1TextualInformation.


        :param definition: The definition of this Product1TextualInformation.
        :type definition: str
        """

        self._definition = definition
